version: '3'

services:
  auth:
    image: auth
    build:
      context: auth
    restart: always
    ports:
      - "8081:8081"
  payment:
    image: payment
    build:
      context: payment
    restart: always
    ports:
      - "8082:8082"
  product:
    image: product
    build:
      context: product
    restart: always
    ports:
      - "8083:8083"
